### PR TITLE
Coco-Stuff 10k dataloader

### PR DESCRIPTION
**Pull request by sayakpaul**
- [x] Host a smaller version of Coco-Stuff 10k
- [x] Write tests for the dataloader.

### CODE REVIEW

**Review by soumik12345 — APPROVED** [review]
@sayakpaul Reviewed the changes, everything seems fine. I have a recommendation that we should update the base dataloader class and make individual dataloaders to be subclasses.

**Comment by soumik12345** [comment]
@sayakpaul Also we should include scipy in the requirements

**Comment by sayakpaul** [comment]
> Reviewed the changes, everything seems fine. I have a recommendation that we should update the base dataloader class and make individual dataloaders to be subclasses.

Might difficult since things are different for Facades and Coco-Stuff 10k. If you have an approach to unify them let me know.

> Also we should include scipy in the requirements

Noted. Could you pop this comment by doing an inline comment on the respective file?

**Comment by sayakpaul** [comment]
Hosted a smaller version of Coco-Stuff 10k for tests: https://github.com/soumik12345/tf2_gans/releases/tag/v0.3.

**Review by soumik12345 — APPROVED** [review]

**Pull request merged**
