### PR TITLE
WandB support

### PR DESCRIPTION
**Pull request by sayakpaul**

### CODE REVIEW

**Comment by sayakpaul** [comment]
ModelCheckpoint callback should be able to handle the case.

**Comment by sayakpaul** [comment]
@soumik12345 up for a review.

**Review by soumik12345 — APPROVED** [review]

**Comment by sayakpaul** [comment]
@soumik12345 when I am running it on Colab I am getting:

```
AttributeError: module 'tensorflow.keras.layers' has no attribute 'Resizing'
```

On the same notebook when I am executing:

```py
from tensorflow import keras
from tensorflow.keras import layers

image_size = 256
kid_image_size = 299

m = keras.Sequential(
    [
        layers.InputLayer(input_shape=(image_size, image_size, 3)),
        layers.Lambda(lambda x: 127.5 * (x + 1)),
        layers.Resizing(height=kid_image_size, width=kid_image_size),
        layers.Lambda(keras.applications.inception_v3.preprocess_input),
        keras.applications.InceptionV3(
            include_top=False,
            input_shape=(kid_image_size, kid_image_size, 3),
            weights="imagenet",
        ),
        layers.GlobalAveragePooling2D(),
    ],
    name="inception_encoder",
)
```

it's executing alright. 

Any clue?

**Comment by sayakpaul** [comment]
Here's the Colab btw. I specified `wandb_project=None` in the config for tests.

**Review by soumik12345 — APPROVED** [review]

**Comment by sayakpaul** [comment]
If everything looks alright, I guess we can merge? @soumik12345

**Pull request merged**
